### ISSUE TITLE
Error: invalid signature: 0x82dd0008

### ISSUE THREAD

**Issue by splincode** [mikermcneil/machinepack-zip#6]
```js

// buildZipSource = "C:\Users\splincode\Git\blackbox\auth\src\main\resources\webapp\default.zip"
// env.distributive = "C:\Users\splincode\Git\blackbox\auth\target\classes\webapp\auth\"

if (fs.existsSync(buildZipSource)) {
        console.log("[Getting assembly from cache]", buildZipSource);

        Zip.unzip({
            source: buildZipSource,
            destination: env.distributive,
        }).exec({
            error: function (err) {
             console.log(err);
            },
            success: function () {
             console.log("[success]");
            },
        });

    }
```

But not working

```text
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0x82dd0008
    at C:\Users\splincode\Git\blackbox\ui-util\node_modules\unzip\lib\parse.js:59:13
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by splincode** [comment]
I use https://www.npmjs.com/package/extract-zip and work
